kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "foldathome"
spec:
  template:
    metadata:
      name: "foldathome"
      namespace: "planblick"
      labels:
        app: "foldathome"
        deploymentconfig: "foldathome"
    spec:
      containers:
        - name: "foldathome"
          image: "registry.gitlab.com/fkdocker/foldathome:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 7396
              protocol: "TCP"
      dnsPolicy: ClusterFirst
  replicas: 1
  selector:
    app: "foldathome"
    deploymentconfig: "foldathome"
  triggers:
    - type: "ConfigChange"
  strategy:
    type: "Rolling"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "foldathome"
  name: "foldathome"
  namespace: "planblick"
spec:
  ports:
    - name: 7396-tcp
      port: 7396
      protocol: TCP
      targetPort: 7396
  selector:
    app: "foldathome"
    deploymentconfig: "foldathome"
  type: ClusterIP
status:
  loadBalancer: {}